"""
Streamlit dashboard — the human-facing view: sentiment trends over time, live
classification, and "ask a question about the comments" (RAG). The FastAPI service
(api/main.py) is the machine-facing view of the same underlying pipeline; the two
share src/ and never duplicate logic.

Run:  streamlit run dashboard/app.py   (run `python train.py` first)
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

import pandas as pd
import streamlit as st

from src.sentiment_model import load_model, predict_sentiment
from src.retriever import load_index
from src.rag_qa import answer_question
from src.monitor import check_drift, log_prediction

ROOT = Path(__file__).parent.parent

st.set_page_config(page_title="YouTube Sentiment MLOps", page_icon="\U0001F4FA", layout="wide")
st.title("YouTube Viewer Sentiment — MLOps Dashboard")
st.caption("Sentiment classification + RAG comment Q&A, with model monitoring built in.")


@st.cache_resource
def get_resources():
    return load_model(), load_index()


@st.cache_data
def get_comments_df():
    return pd.read_csv(ROOT / "data" / "comments.csv", parse_dates=["timestamp"])


try:
    model, retriever_resources = get_resources()
except FileNotFoundError:
    st.error("Model not found. Run `python train.py` from the project root first, then reload.")
    st.stop()

df = get_comments_df()

tab1, tab2, tab3, tab4 = st.tabs(["Overview", "Classify a comment", "Ask about the comments", "Model monitoring"])

with tab1:
    col1, col2, col3 = st.columns(3)
    col1.metric("Total comments", len(df))
    col2.metric("Positive share", f"{(df.sentiment_label == 'positive').mean():.0%}")
    col3.metric("Negative share", f"{(df.sentiment_label == 'negative').mean():.0%}")

    st.subheader("Sentiment distribution")
    st.bar_chart(df["sentiment_label"].value_counts())

    st.subheader("Sentiment over time (daily)")
    daily = df.set_index("timestamp").groupby([pd.Grouper(freq="D"), "sentiment_label"]).size().unstack(fill_value=0)
    st.line_chart(daily)

    st.subheader("By video category")
    st.bar_chart(df.groupby(["video_category", "sentiment_label"]).size().unstack(fill_value=0))

with tab2:
    st.write("Paste a comment to classify it live (this is what `/predict` on the API does).")
    text = st.text_area("Comment text", placeholder="This tutorial was so helpful, thank you!")
    if st.button("Classify", type="primary") and text.strip():
        result = predict_sentiment(model, text)
        log_prediction(text, result["sentiment"], result["confidence"])
        st.metric("Predicted sentiment", result["sentiment"], f"{result['confidence']:.0%} confidence")
        st.json(result["all_scores"])

with tab3:
    st.write("Ask a question about the comment corpus — answers are grounded in retrieved comments (RAG), not invented.")
    question = st.text_input("Question", placeholder="What are viewers complaining about?")
    sentiment_filter = st.selectbox("Restrict to sentiment (optional)", [None, "positive", "neutral", "negative"])
    if st.button("Ask", type="primary") and question.strip():
        result = answer_question(question, retriever_resources, top_k=5, sentiment_filter=sentiment_filter)
        st.info(result["answer"])
        st.caption(f"Generated by: {result['backend']}")
        with st.expander(f"Source comments ({len(result['sources'])})"):
            for s in result["sources"]:
                st.markdown(f"**[{s['sentiment_label']}]** {s['text']}  \n_similarity: {s['similarity']}_")

with tab4:
    st.write(
        "This is the MLOps piece: comparing the sentiment mix of recently classified "
        "comments against the training-set distribution to catch drift before it "
        "silently degrades the model's usefulness."
    )
    if st.button("Run drift check"):
        drift_result = check_drift()
        st.json(drift_result)
    st.caption(
        "Note: this checks predictions logged via the FastAPI `/predict` endpoint "
        "(models/prediction_log.csv) — classify a few comments in the API or the "
        "previous tab first, or run `python -m src.monitor` to simulate some."
    )
